### ISSUE TITLE
Exceptions thrown from sessions writing during install

### ISSUE THREAD

**Issue by agentphoenix** [anodyne/nova3#94]
[2015-02-02 17:54:18] local.ERROR: exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '524fad5c9509eb6f24e0ab3f8de40e01d458837a' for key 'sessions_id_unique'' in /Users/DVS/Sites/nova/dev3/nova/vendor/laravel/framework/src/Illuminate/Database/Connection.php:358
Stack trace:
#0 /Users/DVS/Sites/nova/dev3/nova/vendor/laravel/framework/src/Illuminate/Database/Connection.php(358): PDOStatement->execute(Array)
#1 /Users/DVS/Sites/nova/dev3/nova/vendor/laravel/framework/src/Illuminate/Database/Connection.php(606): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `no...', Array)
#2 /Users/DVS/Sites/nova/dev3/nova/vendor/laravel/framework/src/Illuminate/Database/Connection.php(570): Illuminate\Database\Connection->runQueryCallback('insert into `no...', Array, Object(Closure))
#3 /Users/DVS/Sites/nova/dev3/nova/vendor/laravel/framework/src/Illuminate/Database/Connection.php(359): Illuminate\Database\Connection->run('insert into `no...', Array, Object(Closure))
#4 /Users/DVS/Sites/nova/dev3/nova/vendor/laravel/framework/src/Illuminate/Database/Connection.php(316): Illuminate\Database\Connection->statement('insert into `no...', Array)
#5 /Users/DVS/Sites/nova/dev3/nova/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1701): Illuminate\Database\Connection->insert('insert into `no...', Array)
#6 /Users/DVS/Sites/nova/dev3/nova/vendor/laravel/framework/src/Illuminate/Session/DatabaseSessionHandler.php(88): Illuminate\Database\Query\Builder->insert(Array)
#7 /Users/DVS/Sites/nova/dev3/nova/vendor/laravel/framework/src/Illuminate/Session/Store.php(255): Illuminate\Session\DatabaseSessionHandler->write('524fad5c9509eb6...', 'a:5:{s:6:"_toke...')
#8 /Users/DVS/Sites/nova/dev3/nova/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(90): Illuminate\Session\Store->save()
#9 /Users/DVS/Sites/nova/dev3/nova/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(126): Illuminate\Session\Middleware\StartSession->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#10 /Users/DVS/Sites/nova/dev3/index.php(57): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#11 {main}

Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '524fad5c9509eb6f24e0ab3f8de40e01d458837a' for key 'sessions_id_unique' (SQL: insert into `nova_sessions` (`id`, `payload`, `last_activity`) values (524fad5c9509eb6f24e0ab3f8de40e01d458837a, YTo1OntzOjY6Il90b2tlbiI7czo0MDoidmNQV2ZSTTZOM083OGlldG9mNHpmazdHMWJ4NnUzclN6TDVXNHoxdCI7czoyMjoiUEhQREVCVUdCQVJfU1RBQ0tfREFUQSI7YTowOnt9czo5OiJfcHJldmlvdXMiO2E6MTp7czozOiJ1cmwiO3M6NDM6Imh0dHA6Ly9ub3ZhMy5kZXYvc2V0dXAvaW5zdGFsbC9ub3ZhL3N1Y2Nlc3MiO31zOjk6Il9zZjJfbWV0YSI7YTozOntzOjE6InUiO2k6MTQyMjg5OTY1ODtzOjE6ImMiO2k6MTQyMjg5OTY1ODtzOjE6ImwiO3M6MToiMCI7fXM6NToiZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==, 1422899658))' in /Users/DVS/Sites/nova/dev3/nova/vendor/laravel/framework/src/Illuminate/Database/Connection.php:614
Stack trace:
#0 /Users/DVS/Sites/nova/dev3/nova/vendor/laravel/framework/src/Illuminate/Database/Connection.php(570): Illuminate\Database\Connection->runQueryCallback('insert into `no...', Array, Object(Closure))
#1 /Users/DVS/Sites/nova/dev3/nova/vendor/laravel/framework/src/Illuminate/Database/Connection.php(359): Illuminate\Database\Connection->run('insert into `no...', Array, Object(Closure))
#2 /Users/DVS/Sites/nova/dev3/nova/vendor/laravel/framework/src/Illuminate/Database/Connection.php(316): Illuminate\Database\Connection->statement('insert into `no...', Array)
#3 /Users/DVS/Sites/nova/dev3/nova/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1701): Illuminate\Database\Connection->insert('insert into `no...', Array)
#4 /Users/DVS/Sites/nova/dev3/nova/vendor/laravel/framework/src/Illuminate/Session/DatabaseSessionHandler.php(88): Illuminate\Database\Query\Builder->insert(Array)
#5 /Users/DVS/Sites/nova/dev3/nova/vendor/laravel/framework/src/Illuminate/Session/Store.php(255): Illuminate\Session\DatabaseSessionHandler->write('524fad5c9509eb6...', 'a:5:{s:6:"_toke...')
#6 /Users/DVS/Sites/nova/dev3/nova/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(90): Illuminate\Session\Store->save()
#7 /Users/DVS/Sites/nova/dev3/nova/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(126): Illuminate\Session\Middleware\StartSession->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#8 /Users/DVS/Sites/nova/dev3/index.php(57): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#9 {main}

**Comment by agentphoenix** [comment]
Haven't seen this happen on Windows so far. :confused:
